server:
  port: 8081
spring:
  datasource:
    # You must use PostgreSql database
    url: jdbc:postgresql://localhost:5432/${your-database-name}
    driver-class-name: org.postgresql.Driver
    password: ${your-database-password}
    username: ${your-database-username}
  jpa:
    hibernate:
      ddl-auto: # update, create, create-drop, ...
    show-sql: false
  main:
    allow-circular-references: true
bot:
  token: ${your-bot-token}
  username: ${your-bot-username}
