server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: Ayyub0906
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    allow-circular-references: true
bot:
  token: 5407594116:AAHRCYcGuFK3lClH0cnzxGO-tGywP6uDYXQ
  username: musicplaylister_bot
